application: follow-backend
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
- url: /stylesheets
  static_dir: stylesheets
- url: /static
  static_dir: static
- url: /images
  static_dir: images

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: django
  version: latest
